### PR TITLE
emaidParam.v1.json - change max size to 18

### PR DESCRIPTION
**Pull request by guillaumeFRANCOIS**

### CODE REVIEW

**Comment by steffenrhinow** [comment]
The description is missing that separators will be normalized by the system due to ISO restrictions. Please add before just extending the string

**Comment by MKeCharIN** [comment]
Extension the string to 36 characters suggested.
To be checked till next  meeting and additional pull request to be created.

**Comment by MKeCharIN** [comment]
size of 36 characters is agreed.
Additional pull request to be done.

**Comment by guillaumeFRANCOIS** [comment]
Modification done. Also i changed the pattern because if we want to accept the OCPI contract_id as a potential input for the emaid it is then 36 char long of type ASCII (see https://github.com/ocpi/ocpi/blob/master/mod_cdrs.asciidoc#145-cdrtoken-class)

**Comment by MKeCharIN** [comment]
Be mire specific and define the format like "^[A-Za-z]{2}[-]?\\w{3}[-]?\\w{9**,31**}[-]?(\\w{1})?$""
Update by Guillaume

**Pull request merged**
