### PR TITLE
Add OPNC-from and OPNC-to headers for subOperator identification

### PR DESCRIPTION
**Pull request by guillaumeFRANCOIS**

### CODE REVIEW

**Comment by steffenrhinow** [comment]
I'm do not recommend to add just new stuff to the existing functioning APIs and Processes. If no many options are defined in a protocol, the usage of it will be wild west and chaos. We need a simple and clear way on cummincation level. What is the actuall benefit?

in case of an incident the caller gets a error and the reason from the system - if this needs to propagated -> the caller can forward to its caller, but doesnt need to
the group never decided to be OCPI compliant or similar

**Comment by MKeCharIN** [comment]
General Change with potential, but not yet to be implemented.
If real use-case is shown and all potential negative implications are analyzed, this can be discussed in the following meeting.

**Comment by guillaumeFRANCOIS** [comment]
In today's world of electromobility and roaming, CPO and EMSP operators often delegate the management of their communication flows to entities called supervisors, which may be attached to the same company as the operator they represent, or be a third-party company specializing in this flow management (such as SAP for CPOs).  
A supervisor (back-office/end provider) can therefore manage the flows of one or more operators, which may be of different nature.  This reality in the world of roaming can also be applied to Plug&Charge for EMSP and CPO players, as well as for OEMs, whose major automotive multinationals (Stellantis, Volkswagen, etc.) will certainly be pooling their calls to Plug&Charge platforms for the brands they represent (e.g. SEAT, Volkswagen and Skoda for the Volkswagen group).
When the Plug&Charge platform receives an incoming call, it needs to know which operator the caller represents in order to process the call correctly. Indeed, depending on the nature of the operator and the contract signed between this operator and the Plug&Charge platform, the same controls or services are not applied. 

Also, symmetrically, for outgoing calls from the Plug&Charge platform, like for notifications for example, the entity receiving the call needs to be able to determine simply and reliably for which operator the call is intended. This identification of the operator could sometimes be done in certain flows that carry attributes such as the EMAID or PCID, from which an identifier to identify the operator can be extracted. However, this only represents a fraction of the services in which these identifiers transit. This also requires all players to respect the format of these identifiers to the letter (Kor mentioned that the EMAID standard was applied mainly in Europe and not so much elsewhere). Finally, this system doesn't work for CPOs. 
 
Gireve proposes to manage this operator identification on all OPNC calls in a systematic, simple and clear way, on the principle of OPNC-from headers to be filled in for incoming calls (from the supervisor to the plug&charge platform) and OPNC-to for outgoing calls (from the plug&charge platform to the supervisor) valued with the operator's country code and party id defined by the eMI3 standard.

**Comment by steffenrhinow** [comment]
The clear identifier is the WMI for the OEM, ProviderID for the MO and the OperatorID of the CPO. Aggregators are already using the given concept - which includes VW Group, Has2be/Chargepoint etc. without adding more input over headers. So why creating this overhead with redundant data?

**Comment by kmeelker-cpi** [comment]
The identifiers are clear for the OEM, MO and CPO. And they should be used in the TO and FROM fields in the header. And to follow this concept, the entities within the PKI EcoSystem need an identifier so that they can be addressed.

**Comment by MKeCharIN** [comment]
Comments as conclusion of todays discussion will be made by Kor Meelker.
Than new pull request to be made.

**Comment by MKeCharIN** [comment]
For potential additional player in between the transfer of the encrypted Certificates, the sender and receiver party type and identification (WMI, ProviderID, OperatorID, EVCCID, PKI-System, PoolID, etc.) shall be in the header additionally made available.

Separate call to between Koer, Guillaume, Steffen to define the identifier and make code proposal in this pull request.

**Comment by guillaumeFRANCOIS** [comment]
Following the workhop with Kor and Steffen, I've adapted the merge request. Here's the new format for OPNC-for and OPNC-to headers based on what we discussed.
image

**Comment by guillaumeFRANCOIS** [comment]
@MKeCharIN  i've fixed the merge conflicts. You can merge the PR now

**Comment by MKeCharIN** [comment]
Thanks!

**Pull request merged**
